version: '3'
services:

  mysql:
      image: mysql:8.0
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports: 
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_USER: crawler
          MYSQL_PASSWORD: crawler
          MYSQL_DATABASE: jobdata
      volumes:
          - ./data/mysql:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0
      links: 
          - mysql:db
      ports:
          - 8000:80
      depends_on:
        - mysql

  crawler:
    image: gongzuo_image
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    command: pipenv run python scheduler.py
    restart: "no"

  webapp:
    image: gongzuo_image
    working_dir: /
    command: pipenv run python -m gongzuo.web.app
    restart: "no"
    ports:
      - 5000:5000
    depends_on:
      - crawler
      - mysql